gui:
  nerdFontsVersion: "3"
  showRandomTip: false
  shrinkSidePanelsToContent: true
  expandFocusedSidePanel: true
  showCommandLog: false
  theme:
    activeBorderColor:
      - "#bfbfbf"
      - bold
    inactiveBorderColor:
      - "#000000"
    searchingActiveBorderColor:
      - "#f9e2af"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#1d1d1d"
    cherryPickedCommitBgColor:
      - "#2c2c2c"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#e3e3e3"
