# Tmux Plugin
set -g @plugin "tmux-plugins/tpm"
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "ofirgall/tmux-window-name"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "sainnhe/tmux-fzf"
set -g @plugin "tmux-plugins/tmux-continuum"
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'emretuna/tmux-layouts'

set -g extended-keys on
set -g extended-keys-format csi-u

# Layout
set -g @tmux_layouts_default "vstack"
set -g @tmux_layouts_leader_pane_percentage "50"
unbind t
set -g @tmux_layouts_new_pane_key "t"
bind n next-window

# Start window and pane numbering at 1 (instead of 0)
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Vim Config
# Use Vim shortcuts in copy mode
set-window-option -g mode-keys vi
# Eliminate escape decay delays
set -s escape-time 0
# Mimic Vim visual selection and copying
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
# Fix colors for Neovim
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# Reload Keybind
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Status bar
set -g status on
set -g status-interval 1
set -g status-style "fg=#a9a9a9,bg=default"

set -g status-left-length 40
set -g status-right-length 120

set -g status-left "#{?client_prefix,#[fg=#f9e2af,bold] · PREFIX,}"

set -g status-right "#[fg=#cba6f7,bold]#S #[fg=#a6e3a1,bold]#H #[fg=#89b4fa,bold]%H:%M"

setw -g window-status-format " #[fg=#585b70]#I:#[fg=#a9a9a9]#W "
setw -g window-status-current-format " #[fg=#89b4fa,bold]#I:#W "
setw -g window-status-separator ""

setw -g window-status-activity-style "fg=#f9e2af"
setw -g window-status-bell-style "fg=#f38ba8,bold"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "~/.tmux/plugins/tpm/tpm"
